package com.student.api.dto.user;

import com.student.api.annotation.validator.postalcode.PostalCode;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Valid
@NoArgsConstructor
public class AddressDto {
    @Schema(
            accessMode = Schema.AccessMode.READ_ONLY,
            description = "Id of address, autogenerated value, please ignore for POST operations"
    )
    private Long id;

    @NotNull
    @Schema(
            example = "1"
    )
    private Long voivodeshipId;

    @NotNull
    @NotBlank
    @Schema(
            example = "Gliwice"
    )
    @Size(min = 2, max = 50)
    private String city;

    @NotNull
    @NotBlank
    @PostalCode
    @Schema(
            example = "44-100"
    )
    @Size(min = 6, max = 6)
    private String postalCode;

    @NotNull
    @NotBlank
    @Schema(
            example = "Kaszubska"
    )
    @Size(min = 2, max = 80)
    private String street;

    @NotNull
    @NotBlank
    @Schema(
            example = "23"
    )
    @Size(min = 1, max = 8)
    private String buildingNumber;
}
