package com.student.api.dto.user;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Valid
@NoArgsConstructor
public class CompetencyInformationDto {
    @Schema(
            accessMode = Schema.AccessMode.READ_ONLY,
            description = "Id of competency information, autogenerated value, please ignore for POST operations"
    )
    private Long id;

    @Schema(
            example = "Inż"
    )
    @Size(min = 1, max = 50)
    @NotNull
    private String title;

    @NotNull
    @Size(min = 1, max = 500)
    private String description;
}
