package com.student.api.dto.user;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Valid
@NoArgsConstructor
public class ServiceTypeDto {
    @Schema(
            accessMode = Schema.AccessMode.READ_ONLY,
            description = "Id of service type, autogenerated value, please ignore for POST operations"
    )
    private Long id;

    @NotNull
    @NotBlank
    @Size(min = 1, max = 100)
    private String name;

    @NotNull
    @Schema(example = "01:00:00", accessMode = Schema.AccessMode.READ_ONLY)
    private String durationTime;

    @Size(min = 1, max = 200)
    private String description;

    @NotNull
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private Long doctorId;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private Boolean enabled;
}
